version: "3.7"

services:
  front:
    container_name: kinouz_front
    image: kinouz_front
    volumes:
      - staticbuild:/app/out
    build: .
    ports:
      - 3002:3002

volumes:
  staticbuild: